{{- $fullName := include "extractable-management.fullname" . -}}
{{- $postgres := (include "merged.postgres" . ) | fromYaml }}
{{- $ca := (include "merged.ca" . ) | fromYaml }}
{{- $tracingUrl := include "extractable-management.tracingUrl" . -}}
{{- $metricsUrl := include "extractable-management.metricsUrl" . -}}
{{- if .Values.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-configmap" (include "extractable-management.fullname" .) }}
  labels:
    {{- include "extractable-management.labels" . | nindent 4 }}
data:
  REQUEST_PAYLOAD_LIMIT: {{ .Values.env.requestPayloadLimit | quote }}
  RESPONSE_COMPRESSION_ENABLED: {{ .Values.env.responseCompressionEnabled | quote }}
  LOG_LEVEL: {{ .Values.env.logLevel | quote }}
  DB_TYPE: "postgres"
  DB_HOST: {{ quote $postgres.host }}
  DB_PORT: {{ quote $postgres.port }}
  DB_NAME: {{ $postgres.name | quote }}
  DB_CERT_PATH: /tmp/certs/{{ $postgres.ssl.certFileName }}
  DB_KEY_PATH: /tmp/certs/{{ $postgres.ssl.keyFileName }}
  DB_CA_PATH: /tmp/certs/{{ $postgres.ssl.caFileName }}
  DB_ENABLE_SSL_AUTH: {{ $postgres.ssl.enabled | quote }}
  LOG_PRETTY_PRINT_ENABLED: {{ .Values.env.logPrettyPrintEnabled | quote }}
  {{- if .Values.env.tracing.enabled }}
  TELEMETRY_TRACING_ENABLED: 'true'
  TELEMETRY_TRACING_URL: {{ $tracingUrl }}
  {{- end }}
  {{- if .Values.env.metrics.enabled }}
  TELEMETRY_METRICS_ENABLED: 'true'
  TELEMETRY_METRICS_URL: {{ $metricsUrl }}
  {{- end }}
  npm_config_cache: /tmp/
  NODE_CONFIG_DIR: /etc/config
  NODE_ENV: production
  SUPPRESS_NO_CONFIG_WARNING: 'false'
  production.json: |
    {
      "server": {
        "port": 8080
      },
      "db": {
        "host": {{ quote $postgres.host }},
        "port": {{ $postgres.port }},
        "name": {{ quote $postgres.name }}
      }
    }
  {{- with .Values.configManagement }}
  CONFIG_NAME: {{ .name| quote }}
  CONFIG_VERSION: {{ .version | quote }}
  CONFIG_OFFLINE_MODE: {{ .offlineMode | quote }}
  CONFIG_SERVER_URL: {{ .serverUrl | quote }}
  {{- end -}}
  {{- if $ca.enabled }}
  REQUESTS_CA_BUNDLE: {{ printf "%s/%s" $ca.path $ca.key | quote }}
  NODE_EXTRA_CA_CERTS: {{ printf "%s/%s" $ca.path $ca.key | quote }}
  {{- end }}
{{- end }}
