{{- $releaseName := .Release.Name -}}
{{- $chartName := include "extractable-management.name" . -}}
{{- $fullname := include "extractable-management.fullname" . -}}
{{- $cloudProviderDockerRegistryUrl := include "extractable-management.cloudProviderDockerRegistryUrl" . -}}
{{- $cloudProviderImagePullSecretName := include "extractable-management.cloudProviderImagePullSecretName" . -}}
{{- $imageTag := include "extractable-management.tag" . -}}
{{- $postgres := include "merged.postgres" . | fromYaml -}}

{{- if .Values.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-deployment" $fullname }}
  labels:
    app: {{ $chartName }}
    component: {{ $chartName }}
    release: {{ $releaseName }}
    {{- include "extractable-management.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      app: {{ $chartName }}
      release: {{ $releaseName }}
      run: {{ $releaseName }}-{{ $chartName }}
      {{- include "extractable-management.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: {{ $chartName }}
        release: {{ $releaseName }}
        run: {{ $releaseName }}-{{ $chartName }}
        {{- include "extractable-management.labels" . | nindent 8 }}
      annotations:
        {{ include "mclabels.annotations" . | nindent 8 }}
        {{- if .Values.resetOnConfigChange }}
        checksum/configmap: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- end }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- if $cloudProviderImagePullSecretName }}
      imagePullSecrets:
        - name: {{ $cloudProviderImagePullSecretName | quote }}
      {{- end }}
      containers:
        - name: {{ $releaseName }}-{{ $chartName }}-deployment
          {{- with .Values.image }}
          image: {{ $cloudProviderDockerRegistryUrl }}{{ .repository }}:{{ $imageTag }}
          imagePullPolicy: {{ .pullPolicy | default "IfNotPresent" }}
          {{- end }}

          {{- with .Values.command }}
          command:
            {{ toYaml . | nindent 12 }}
            {{- with $.Values.args }}
          args:
            {{ toYaml . | nindent 12 }}
            {{- end }}
          {{- end }}

          ports:
            - name: http
              containerPort: {{ .Values.env.targetPort }}
              protocol: {{ default "TCP" .Values.env.protocol }}

          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ $postgres.user.secretName }}
                  key: username
            {{- if $postgres.user.requirePassword }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ $postgres.user.secretName }}
                  key: password
            {{- end }}
            {{- with .Values.extraEnvVars }}
            {{ toYaml . | nindent 12 }}
            {{- end }}

          envFrom:
            - configMapRef:
                name: {{ printf "%s-configmap" $fullname }}

          {{- if .Values.resources.enabled }}
          resources:
            {{ toYaml .Values.resources.value | nindent 12 }}
          {{- end }}

          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.path }}
              port: {{ .Values.env.targetPort }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          {{- end }}

          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.path }}
              port: {{ .Values.env.targetPort }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
          {{- end }}

          {{- with .Values.extraVolumeMounts }}
          volumeMounts:
            {{ toYaml . | nindent 12 }}
          {{- end }}

        {{- with .Values.sidecars }}
        {{ tpl (toYaml .) $ | nindent 8 }}
        {{- end }}

      volumes:
        - name: nginx-config
          configMap:
            name: 'nginx-extra-configmap'

        {{- if and $postgres.enabled $postgres.ssl.enabled }}
        - name: postgres-cert
          secret:
            secretName: {{ $postgres.ssl.secretName }}
        {{- end }}

        {{- if .Values.caSecretName }}
        - name: root-ca
          secret:
            secretName: {{ .Values.caSecretName }}
        {{- end }}

        {{- with .Values.extraVolumes }}
        {{ tpl (toYaml .) $ | nindent 8 }}
        {{- end }}

{{- end }}
