{{- $releaseName := .Release.Name -}}
{{- $chartName := include "extractable-management.name" . -}}
{{- $cloudProviderFlavor := include "extractable-management.cloudProviderFlavor" . -}}
{{- $cloudProviderDockerRegistryUrl := include "extractable-management.cloudProviderDockerRegistryUrl" . -}}
{{- $cloudProviderImagePullSecretName := include "extractable-management.cloudProviderImagePullSecretName" . -}}
{{- $imageTag := include "extractable-management.tag" . -}}
{{- $postgres := include "merged.postgres" . | fromYaml }}
{{- if .Values.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-deployment" (include "extractable-management.fullname" .) }}
  labels:
    app: {{ $chartName }}
    component: {{ $chartName }}
    release: {{ $releaseName }}
    {{- include "extractable-management.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      app: {{ $chartName }}
      release: {{ $releaseName }}
      run: {{ $releaseName }}-{{ $chartName }}
      {{- include "extractable-management.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: {{ $chartName }}
        release: {{ $releaseName }}
        run: {{ $releaseName }}-{{ $chartName }}
        {{- include "extractable-management.labels" . | nindent 8 }}
      annotations:
        {{ include "mclabels.annotations" . | nindent 8 }}
      {{- if .Values.resetOnConfigChange }}
        checksum/configmap: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      {{- end }}
      {{- if .Values.podAnnotations }}
      {{- toYaml .Values.podAnnotations | nindent 8 }}
      {{- end }}
    spec:
    {{- if $cloudProviderImagePullSecretName }}
      imagePullSecrets:
        - name: {{ $cloudProviderImagePullSecretName | quote }}
    {{- end }}
      containers:
        - name: {{ $releaseName }}-{{ $chartName }}-deployment
          {{- with .Values.image }}
          image: {{ $cloudProviderDockerRegistryUrl }}{{ .repository }}:{{ $imageTag }}
          imagePullPolicy: {{ .pullPolicy | default "IfNotPresent" }}
          {{- end }}
          {{- if .Values.command }}
          command: 
          {{- toYaml .Values.command | nindent 12 }}
          {{- if .Values.args }}
          args: 
          {{- toYaml .Values.args | nindent 12 }}
          {{- end }}
          {{- end }}
          volumeMounts:
            {{- if .Values.caSecretName }}
            - mountPath: {{ printf "%s/%s" .Values.caPath .Values.caKey | quote }}
              name: root-ca
              subPath: {{ quote .Values.caKey }}
            {{- end }}
            {{- if .Values.extraVolumeMounts -}}
              {{ toYaml .Values.extraVolumeMounts | nindent 12 }}
            {{- end }}
          env:
            - name: SERVER_PORT
              value: {{ .Values.env.targetPort | quote }}
            - name: USERS_JSON
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.usersSecret.name }}
                  key: {{ .Values.usersSecret.key }}
            {{- if $postgres.enabled }}
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ $postgres.user.secretName }}
                  key: username
            {{- if $postgres.user.requirePassword }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ $postgres.user.secretName }}
                  key: password
            {{- end }}
            {{- end }}
            {{- if .Values.caSecretName }}
            - name: REQUESTS_CA_BUNDLE
              value: {{ printf "%s/%s" .Values.caPath .Values.caKey | quote }}
            - name: NODE_EXTRA_CA_CERTS
              value: {{ printf "[%s/%s]" .Values.caPath .Values.caKey | quote }}
            {{- end }}
            {{- if .Values.extraEnvVars }}
            {{- toYaml .Values.extraEnvVars | nindent 12 }}
            {{- end }}            
          envFrom:
            - configMapRef:
                name: {{ printf "%s-configmap" (include "extractable-management.fullname" .) }}
          ports:
            - name: http
              containerPort: {{ .Values.env.targetPort }}
              protocol: {{ .Values.env.protocol }}
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
            httpGet:
              path: {{ .Values.livenessProbe.path }}
              port: {{ .Values.env.targetPort }}
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
            httpGet:
              path: {{ .Values.readinessProbe.path }}
              port: {{ .Values.env.targetPort }}
          {{- end }}        
          {{- if .Values.resources.enabled }}
          resources:
            {{- toYaml .Values.resources.value | nindent 12 }}
          {{- end }}
        {{- if .Values.sidecars }}
        {{ tpl (toYaml .Values.sidecars) . | nindent 8 }}
        {{- end }}
      volumes:
        - name: nginx-config
          configMap:
            name: 'nginx-extra-configmap'
        {{- if .Values.caSecretName }}
        - name: root-ca
          secret:
            secretName: {{ .Values.caSecretName }}
        {{- end }}
        {{- if $postgres.ssl.enabled }}
        - name: postgres-cert
          secret:
            secretName: {{ $postgres.ssl.secretName }}
        {{- end }}
        {{- if .Values.extraVolumes -}}
          {{ tpl (toYaml .Values.extraVolumes) . | nindent 8 }}
        {{- end }}
{{- end -}}
