apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.usersSecret.name }}
type: Opaque
stringData:
  {{ .Values.usersSecret.key }}: |
    [
      {
        "username": "username",
        "password": "password"
      }
    ]
  extractable-username: extractable_records_test
  extractable-password: extractable_records_password_test
  audit-username: audit_logs_test
  audit-password: audit_logs_password_test
