apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.usersSecret.name }}
type: Opaque
stringData:
  {{ .Values.usersSecret.key }}: |
    [
      {
        "username": "username",
        "password": "password"
      }
    ]
  extractable-username: username_test
  extractable-password: password_test
