apiVersion: v2
name: extractable-management
description: A Helm chart for extractable-management service
type: application
version: 1.0.0
appVersion: 1.0.0
dependencies:
  - name: mclabels
    version: 1.0.1
    repository: oci://acrarolibotnonprod.azurecr.io/helm/infra
  - name: nginx
    version: 1.3.0
    repository: oci://acrarolibotnonprod.azurecr.io/helm
