global:
  cloudProvider: {}
  tracing: {}
  metrics: {}

mclabels:
  component: backend
  partOf: extractable
  owner: 3d
  prometheus:
    enabled: true

enabled: true
replicaCount: 1
revisionHistoryLimit: 5  # Amount of revisions we keep
nodePort: 30030  # for minikube deployment only
resetOnConfigChange: true

nameOverride: ""
fullnameOverride: ""

configManagement:
  offlineMode: true
  name: 'extractable-management'
  version: 'latest'
  serverUrl: 'http://localhost:8080/api'

livenessProbe:
  enabled: true
  initialDelaySeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  path: /liveness

readinessProbe:
  enabled: true
  initialDelaySeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  path: /liveness

podAnnotations: {}

extraVolumes: []

extraVolumeMounts: []

extraEnvVars: []

command: []
args: []
# command: [ "/bin/sh", "-c", "--" ]
# args: [ "while true; do sleep infinity; done;" ]

sidecars: []

cloudProvider:
  dockerRegistryUrl: ''
  imagePullSecretName: ''
  flavor: openshift

caSecretName: ''
caPath: '/usr/local/share/ca-certificates'
caKey: 'ca.crt'

image:
  repository: extractable-management
  tag:

env:
  port: 8080
  targetPort: 8080
  protocol: TCP
  logLevel: info
  logPrettyPrintEnabled: false
  responseCompressionEnabled: true
  requestPayloadLimit: 1mb
  tracing:
    enabled: false
    url: http://localhost:55681/v1/trace
  metrics:
    enabled: false
    url: http://localhost:55681/v1/metrics

resources:
  enabled: true
  value:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

nginx:
  nginx:
    maxAge: 1728000
  enabled: true
  fullnameOverride: ""

  caSecretName: ''
  caPath: '/usr/local/share/ca-certificates'
  caKey: 'ca.crt'

  image:
    repository: nginx
    tag: 'latest' 
  port: 8080
  targetPort: 8080
  nodePort: 30001

  authorization:
    enabled: false
    domain: "3d"
    url: 'http://localhost:8181/v1/data/http/authz/decision'
    token:
      queryName: token

  route:
    enabled: true
    # routesMapping:
    #   - host: tiles-dev.mapcolonies.net
    #     path: /api/raster/v1
    tls:
      enabled: true
      useCerts: false
      # certificate: *certificate
      # key: *key
      # caCertificate: *caCertificate
    timeout:
      enabled: false # defaults to 30s by openshift
      duration: 60s # supported units (us, ms, s, m, h, d)

  resources:
    enabled: true
    value:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi

  extraVolumes:
    - name: nginx-config
      configMap:
        name: "{{ .Release.Name }}-extractable-management-nginx-configmap"

  extraVolumeMounts:
    - name: nginx-config
      mountPath: "/etc/nginx/conf.d/default.conf"
      subPath: default.conf
    - name: nginx-config
      mountPath: "/etc/nginx/nginx.conf"
      subPath: nginx.conf
    - name: nginx-config
      mountPath: "/etc/nginx/log_format.conf"
      subPath: log_format.conf

  env:
    opentelemetry:
      serviceName: nginx
      exporterEndpoint: localhost:4317
      samplerMethod: "AlwaysOff" # AlwaysOn, AlwaysOff, TraceIdRatioBased
      ratio: 0.1 # between 0 and 1
      parentBased: "false" # true, false

  prometheusExporter:
    enabled: false
    image:
      repository: nginx/nginx-prometheus-exporter
      tag: latest
      pullPolicy: IfNotPresent
    resources:
      enabled: true
      value:
        limits:
          cpu: 100m
          memory: 128Mi
        requests:
          cpu: 100m
          memory: 128Mi

route:
  enabled: false

ingress:
  enabled: false
  path: /
  host: 'localhost'
  cors:
    enabled: true
    origin: '*'

usersSecret:
  name: extractable-management-users-secret
  key: users-json

postgres:
  enabled: true
  user:
    useExternal: false
    secretName: extractable-management-db-secrets
    requirePassword: true
  ssl:
    enabled: false
